<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2016/9/21
 * Time: 11:02
 */

namespace app\demo\controller;


use app\demo\model\User;
use think\Controller;
use think\Request;
use think\Session;

class Base extends controller
{
  public function _initialize()
  {
      //动态绑定request的属性
      parent::_initialize(); // TODO: Change the autogenerated stub
      session('user_id','1');
      $user=User::get(Session::get('user_id'));

      Request::instance()->bind('user',$user);//将URL模型的request对象属性上
  }
}