<?php
// +----------------------------------------------------------------------
// | ThinkPHP [ WE CAN DO IT JUST THINK ]
// +----------------------------------------------------------------------
// | Copyright (c) 2006-2016 http://thinkphp.cn All rights reserved.
// +----------------------------------------------------------------------
// | Licensed ( http://www.apache.org/licenses/LICENSE-2.0 )
// +----------------------------------------------------------------------
// | Author: 流年 <liu21st@gmail.com>
// +----------------------------------------------------------------------

// 应用公共文件

/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2016/9/21
 * Time: 11:02
 */

namespace app;

use app\demo\model\User;
use think\Controller;
use think\Request;
use think\Session;

class common extends controller
{
    public function _initialize()
    {
        //动态绑定request的属性
        parent::_initialize(); // TODO: Change the autogenerated stub
        session('user_id','1');
        $user=User::get(Session::get('user_id'));

        Request::instance()->bind('user',$user);//将URL模型的request对象属性上
    }
}